version: 0.1
log:
  level: info
http:
  secret: "mysecretkey"
  addr: :5000
  headers:
    X-Content-Type-Options: [nosniff]
    Access-Control-Allow-Origin: ["http://localhost:8080"]
    Access-Control-Allow-Methods: ["GET, PUT, DELETE, POST, OPTIONS"]
    Access-Control-Allow-Headers: ["Authorization, Content-Type"]
    Access-Control-Allow-Credentials: [true]
storage:
  filesystem:
    rootdirectory: /var/lib/registry