services:
  registry:
    image: registry:2
    container_name: my_registry
    ports:
      - "5000:5000"
    volumes:
      - ./data:/var/lib/registry
    networks:
      - app_network

  registry-ui:
    image: joxit/docker-registry-ui:latest
    container_name: registry_ui
    ports:
      - "8080:80"
    environment:
      - REGISTRY_URL=http://registry:5000 
    depends_on:
      - registry
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
