services:
  api:
    build: ./simple_api
    ports:
      - "5000:5000"  
    volumes:
      - data:/data  
      - ./simple_api/student_age.json:/data/student_age.json
    networks:
      - api_network 

  website:
    image: php:apache 
    volumes:
      - ./website:/var/www/html 
    depends_on:
      - api
    ports:
      - "80:80"  
    environment:
      - USERNAME=root 
      - PASSWORD=root
    networks:
      - api_network

networks:
  api_network:

volumes:
  data: 
