services:
  registry:
    image: registry:2
    container_name: my_registry
    ports:
      - "5001:5000"
    volumes:
      - ./data:/var/lib/registry
      - ./config.yml:/etc/docker/registry/config.yml
    networks:
      - registry_network

  registry-ui:
    image: joxit/docker-registry-ui:latest
    container_name: registry_ui
    ports:
      - "8080:80"
    environment:
      - REGISTRY_TITLE=MyRegistry
      - REGISTRY_URL=http://localhost:5001 
      - REGISTRY_HTTP_SECRET=mysecretkey
    depends_on:
      - registry
    networks:
      - registry_network

networks:
  registry_network:
    driver: bridge